### ISSUE TITLE
The confirm purchase menu does not close when you "confirm - yes" your purchase (Tried to fix it using the DEV's method)

### ISSUE THREAD

**Issue by TheBGamer** [esx-framework/esx_clotheshop#18]
![293405880-ae076024-e109-4750-86f2-507cd1fbf753](https://github.com/esx-framework/esx_clotheshop/assets/87948499/da0b4916-6219-4928-a4c3-0edd1f11217c)

**Comment by Gellipapa** [comment]
@TheBGamer Hi! For some reason, your datastore didn't register the property data store and didn't find the key and that's why you get the error.

If your datastore has the property properly registered you should not have this problem. 

I recommend a re-download and datastore setup in your property system.
